/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { NavigationRoute, registerRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { ExpirationPlugin } from 'workbox-expiration';

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

clientsClaim();

// Precache all assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// Allow work offline
registerRoute(new NavigationRoute(createHandlerBoundToURL('index.html')));

// ---------------------------------------------------------------------------
// 1. API Caching Strategies
// ---------------------------------------------------------------------------

// Background Sync for failed messages
const bgSyncPlugin = new BackgroundSyncPlugin('entropy-queue', {
    maxRetentionTime: 24 * 60, // Retry for max of 24 Hours (specified in minutes)
});

// Sync Endpoint - Network Only with Background Sync
// NetworkFirst tries to cache the response, which fails for POST.
// We use NetworkOnly because we don't need to read the response from cache, 
// we only need to queue failed requests.
import { NetworkOnly } from 'workbox-strategies';

registerRoute(
    ({ url }) => url.pathname.startsWith('/api/sync') || url.pathname.startsWith('/api/messages'),
    new NetworkOnly({
        plugins: [bgSyncPlugin],
        networkTimeoutSeconds: 10,
    }),
    'POST'
);

// General API - Network First, fall back to cache for reading data
registerRoute(
    ({ url }) => url.pathname.startsWith('/api/'),
    new NetworkFirst({
        cacheName: 'api-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 60 * 60 * 24, // 1 day
            }),
        ],
        networkTimeoutSeconds: 5,
    }),
    'GET'
);

// ---------------------------------------------------------------------------
// 2. Asset Caching Strategies
// ---------------------------------------------------------------------------

// Images (Avatars, Uploads) - StaleWhileRevalidate for freshness but speed
registerRoute(
    ({ request }) => request.destination === 'image',
    new StaleWhileRevalidate({
        cacheName: 'images',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

// Fonts - Cache First
registerRoute(
    ({ request }) => request.destination === 'font',
    new CacheFirst({
        cacheName: 'fonts',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 30,
            }),
        ],
    })
);

// Media (Audio/Video) - Cache First (since ringtone doesn't change)
registerRoute(
    ({ request }) => request.destination === 'audio' || request.destination === 'video' || request.url.endsWith('ringtone.mp3'),
    new CacheFirst({
        cacheName: 'media-v2', // Bump version to force refresh
        plugins: [
            new ExpirationPlugin({
                maxEntries: 20,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

// ---------------------------------------------------------------------------
// 3. Push Notifications
// ---------------------------------------------------------------------------

interface NotificationAction {
    action: string;
    title: string;
    icon?: string;
}

interface ExtendedNotificationOptions extends NotificationOptions {
    actions?: NotificationAction[];
    renotify?: boolean;
    vibrate?: number[];
    requireInteraction?: boolean;
}

self.addEventListener('push', (event) => {
    const data = event.data ? event.data.json() : {};
    const title = data.title || 'Entropy Notification';
    const type = data.type || 'message'; // 'message' | 'call' | 'system'

    // Default options
    const options: ExtendedNotificationOptions = {
        body: data.body || '',
        icon: data.icon || '/pwa-192x192.png',
        badge: '/entropy.svg',
        vibrate: [100, 50, 100],
        data: {
            url: data.url || '/',
            type: type,
            room_id: data.room_id,
            call_id: data.call_id
        },
        actions: []
    };

    // CALL SPECIFIC LOGIC
    if (type === 'call') {
        options.tag = 'call-' + (data.call_id || Date.now()); // Unique tag per call
        options.renotify = true;
        options.requireInteraction = true; // Keep notification on screen
        options.vibrate = [500, 200, 500, 200, 500]; // Longer vibration pattern
        options.actions = [
            { action: 'answer', title: 'Answer' },
            { action: 'decline', title: 'Decline' }
        ];
    }
    // MESSAGE SPECIFIC LOGIC
    else if (type === 'message') {
        options.tag = 'room-' + (data.room_id || 'general'); // Group by room
        options.renotify = true;
        options.actions = [
            { action: 'open', title: 'Reply' },
            { action: 'mark_read', title: 'Mark Read' }
        ];

        // Update App Badge if supported
        if ('setAppBadge' in navigator) {
            // We don't have the exact count here, but we can set a flag or just 1
            // Ideally backend sends count. For now, just set 1 to indicate "something new"
            // or increment if we could track it (sw is statelessish though)
            (navigator as any).setAppBadge(1).catch(() => { });
        }
    }

    event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    const action = event.action;
    // const type = event.notification.data.type; // Unused for now
    const urlToOpen = new URL(event.notification.data.url, self.location.origin).href;

    // Handle Decline (No navigation needed)
    if (action === 'decline') {
        // Optional: Send a request to backend to reject call?
        // For now just closing is fine, the caller will timeout.
        return;
    }

    // Handle Mark Read (Likely needs auth, difficult in SW without tokens in IndexedDB)
    // We'll just open the app for now for simplicity/reliability

    // Handle Answer/Open/Default Click
    const promise = self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
        // 1. Try to find existing window
        for (let i = 0; i < windowClients.length; i++) {
            const client = windowClients[i];
            if (client.url.startsWith(self.location.origin) && 'focus' in client) {
                return client.focus().then((focusedClient) => {
                    // If it's a call answer, maybe we append ?answer=true to URL or use postMessage?
                    // Navigation is safest to ensure context is loaded.
                    if (focusedClient && 'navigate' in focusedClient) {
                        return focusedClient.navigate(urlToOpen);
                    }
                    return focusedClient;
                });
            }
        }
        // 2. Open new window if none
        if (self.clients.openWindow) {
            return self.clients.openWindow(urlToOpen);
        }
    });

    event.waitUntil(promise);
});
