/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'
import { NavigationRoute, registerRoute } from 'workbox-routing'

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

clientsClaim();

// Precache all assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use prec aching. See https://vite-pwa-org.netlify.app/guide/inject-manifest.html
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// Allow work offline
registerRoute(new NavigationRoute(createHandlerBoundToURL('index.html')));

// Push Notifications
self.addEventListener('push', (event) => {
    const data = event.data ? event.data.json() : {};
    const title = data.title || 'Entropy Notification';
    const options = {
        body: data.body || '',
        icon: data.icon || '/entropy.svg',
        badge: '/entropy.svg',
        data: {
            url: data.url || '/'
        }
    };

    event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            const urlToOpen = new URL(event.notification.data.url, self.location.origin).href;

            // Check if there is already a window for this app open
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                // Check if the client matches the origin (basically any window of our app)
                if (client.url.startsWith(self.location.origin) && 'focus' in client) {
                    return client.focus().then((focusedClient) => {
                        // Navigate the focused client to the notification URL
                        if (focusedClient && 'navigate' in focusedClient) {
                            return focusedClient.navigate(urlToOpen);
                        }
                        return focusedClient;
                    });
                }
            }
            // If no window is open, open one
            if (self.clients.openWindow) {
                return self.clients.openWindow(urlToOpen);
            }
        })
    );
});
